language: r
cache: packages
sudo: false
warnings_are_errors: true

before_install:
  - source travis/before-install.sh

r:
  - oldrel
  - release
  - devel

env:
  - CC=gcc-4.4 CXX=g++-4.4
  - CC=gcc CXX=g++
  - CC=clang CXX=clang
