language: r
cache: packages

addons:
  apt:
    packages:
      - gcc-4.4
      - g++-4.4

matrix:
  include:
    - os: linux
      dist: precise
      env: CC=gcc-4.4 CXX=g++-4.4
    - os: linux
      dist: precise
      env: CC=gcc CXX=g++
